package: ycom
version: '3.0dev'
author: Yakamara Media GmbH & Co. KG, concedra GmbH
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:ycom_navi_title'
    perm: ycom[]
    block: ycom
    icon: rex-icon fa-group

requires:
    packages:
        yform: '^3'
        yrewrite: '^2.6'
        phpmailer: '^2.2'
    redaxo: '^5.7'

system_plugins:
    - auth
    - group
    - docs